language: node_js
os: linux
dist: xenial
node_js:
  - '12'
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_install:
  - npm update
install:
  - npm install
script:
  - npm test
  - npm run coveralls
