name: npm-publish
on:
  push:
    tags:
      - v*.*.*
jobs:
  npm-publish:
    name: npm-publish
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout
    - name: Set up Node.js
      uses: actions/setup-node
      with:
        node-version: 12
    - run: npm install
    - run: npm run build
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
